version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamodb-bulk-update"
s3_prefix = "dynamodb-bulk-update"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ConsistentRead=\"true\""
image_repositories = []
